// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class AuthGatePigeonCodecReader: FlutterStandardReader {
}

private class AuthGatePigeonCodecWriter: FlutterStandardWriter {
}

private class AuthGatePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AuthGatePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AuthGatePigeonCodecWriter(data: data)
  }
}

class AuthGatePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AuthGatePigeonCodec(readerWriter: AuthGatePigeonCodecReaderWriter())
}

/// Controls the native auth gate lifecycle.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AuthGateApi {
  /// Called when no session exists.
  func requireLogin() throws
  /// Called after successful login.
  func loginDidComplete() throws
  /// Called when a session exists but the token has expired.
  func reauthRequired() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AuthGateApiSetup {
  static var codec: FlutterStandardMessageCodec { AuthGatePigeonCodec.shared }
  /// Sets up an instance of `AuthGateApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: AuthGateApi?, messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Called when no session exists.
    let requireLoginChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.AuthGateApi.requireLogin\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requireLoginChannel.setMessageHandler { _, reply in
        do {
          try api.requireLogin()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requireLoginChannel.setMessageHandler(nil)
    }
    /// Called after successful login.
    let loginDidCompleteChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.AuthGateApi.loginDidComplete\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loginDidCompleteChannel.setMessageHandler { _, reply in
        do {
          try api.loginDidComplete()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loginDidCompleteChannel.setMessageHandler(nil)
    }
    /// Called when a session exists but the token has expired.
    let reauthRequiredChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.AuthGateApi.reauthRequired\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reauthRequiredChannel.setMessageHandler { _, reply in
        do {
          try api.reauthRequired()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reauthRequiredChannel.setMessageHandler(nil)
    }
  }
}
