// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(
    code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.",
    details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsLogin(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsLogin(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsLogin(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashLogin(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
    for item in valueList { deepHashLogin(value: item, hasher: &hasher) }
    return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashLogin(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

/// Generated class from Pigeon that represents data sent in messages.
struct ServerCheckResult: Hashable {
  var serverType: String? = nil
  var serverUrl: String? = nil
  var version: String? = nil
  var selfSigned: Bool
  var errorKind: String? = nil
  var errorMessage: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServerCheckResult? {
    let serverType: String? = nilOrValue(pigeonVar_list[0])
    let serverUrl: String? = nilOrValue(pigeonVar_list[1])
    let version: String? = nilOrValue(pigeonVar_list[2])
    let selfSigned = pigeonVar_list[3] as! Bool
    let errorKind: String? = nilOrValue(pigeonVar_list[4])
    let errorMessage: String? = nilOrValue(pigeonVar_list[5])

    return ServerCheckResult(
      serverType: serverType,
      serverUrl: serverUrl,
      version: version,
      selfSigned: selfSigned,
      errorKind: errorKind,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      serverType,
      serverUrl,
      version,
      selfSigned,
      errorKind,
      errorMessage,
    ]
  }
  static func == (lhs: ServerCheckResult, rhs: ServerCheckResult) -> Bool {
    return deepEqualsLogin(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashLogin(value: toList(), hasher: &hasher)
  }
}

private class LoginPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ServerCheckResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LoginPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ServerCheckResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LoginPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LoginPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LoginPigeonCodecWriter(data: data)
  }
}

class LoginPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LoginPigeonCodec(readerWriter: LoginPigeonCodecReaderWriter())
}

/// Native login screen callbacks to Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LoginFlutterApiProtocol {
  func checkServer(
    url urlArg: String, selfSigned selfSignedArg: Bool,
    completion: @escaping (Result<ServerCheckResult, PigeonError>) -> Void)
  func loginWallabag(
    url urlArg: String, selfSigned selfSignedArg: Bool, clientId clientIdArg: String,
    clientSecret clientSecretArg: String, username usernameArg: String,
    password passwordArg: String, completion: @escaping (Result<String?, PigeonError>) -> Void)
  func loginFreon(
    url urlArg: String, selfSigned selfSignedArg: Bool, token tokenArg: String,
    completion: @escaping (Result<String?, PigeonError>) -> Void)
  func loadDemoMode(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LoginFlutterApi: LoginFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LoginPigeonCodec {
    return LoginPigeonCodec.shared
  }
  func checkServer(
    url urlArg: String, selfSigned selfSignedArg: Bool,
    completion: @escaping (Result<ServerCheckResult, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LoginFlutterApi.checkServer\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([urlArg, selfSignedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ServerCheckResult
        completion(.success(result))
      }
    }
  }
  func loginWallabag(
    url urlArg: String, selfSigned selfSignedArg: Bool, clientId clientIdArg: String,
    clientSecret clientSecretArg: String, username usernameArg: String,
    password passwordArg: String, completion: @escaping (Result<String?, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(
      [urlArg, selfSignedArg, clientIdArg, clientSecretArg, usernameArg, passwordArg] as [Any?]
    ) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        let result: String? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
  func loginFreon(
    url urlArg: String, selfSigned selfSignedArg: Bool, token tokenArg: String,
    completion: @escaping (Result<String?, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginFreon\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([urlArg, selfSignedArg, tokenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        let result: String? = nilOrValue(listResponse[0])
        completion(.success(result))
      }
    }
  }
  func loadDemoMode(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LoginFlutterApi.loadDemoMode\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
