// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsSync(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsSync(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsSync(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashSync(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
    for item in valueList { deepHashSync(value: item, hasher: &hasher) }
    return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashSync(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

enum SyncIndicatorStatus: Int {
  case allGood = 0
  case syncing = 1
  case noInternet = 2
  case serverUnreachable = 3
  case syncError = 4
  case authFailure = 5
}

/// Generated class from Pigeon that represents data sent in messages.
struct SyncIndicatorState: Hashable {
  var status: SyncIndicatorStatus
  var progressValue: Double? = nil
  var pendingCount: Int64
  var lastSyncTimestamp: Int64? = nil
  var errorDetail: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SyncIndicatorState? {
    let status = pigeonVar_list[0] as! SyncIndicatorStatus
    let progressValue: Double? = nilOrValue(pigeonVar_list[1])
    let pendingCount = pigeonVar_list[2] as! Int64
    let lastSyncTimestamp: Int64? = nilOrValue(pigeonVar_list[3])
    let errorDetail: String? = nilOrValue(pigeonVar_list[4])

    return SyncIndicatorState(
      status: status,
      progressValue: progressValue,
      pendingCount: pendingCount,
      lastSyncTimestamp: lastSyncTimestamp,
      errorDetail: errorDetail
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      progressValue,
      pendingCount,
      lastSyncTimestamp,
      errorDetail,
    ]
  }
  static func == (lhs: SyncIndicatorState, rhs: SyncIndicatorState) -> Bool {
    return deepEqualsSync(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashSync(value: toList(), hasher: &hasher)
  }
}

private class SyncPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SyncIndicatorStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return SyncIndicatorState.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SyncPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SyncIndicatorStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SyncIndicatorState {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SyncPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SyncPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SyncPigeonCodecWriter(data: data)
  }
}

class SyncPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SyncPigeonCodec(readerWriter: SyncPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SyncApi {
  func updateSyncState(state: SyncIndicatorState) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SyncApiSetup {
  static var codec: FlutterStandardMessageCodec { SyncPigeonCodec.shared }
  /// Sets up an instance of `SyncApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: SyncApi?, messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateSyncStateChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.SyncApi.updateSyncState\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSyncStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = args[0] as! SyncIndicatorState
        do {
          try api.updateSyncState(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateSyncStateChannel.setMessageHandler(nil)
    }
  }
}
