repos:
  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        language: system
        entry: fvm dart format
        types: [file]
        files: \.dart$

      - id: translations
        name: translations
        language: system
        entry: make translations
        files: (lib/l10n/.*\.arb|fastlane/metadata/.*)$
        pass_filenames: false

  - repo: https://github.com/swiftlang/swift-format
    rev: 602.0.0
    hooks:
      - id: swift-format
