// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(
    code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.",
    details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsSettings(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsSettings(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsSettings(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashSettings(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
    for item in valueList { deepHashSettings(value: item, hasher: &hasher) }
    return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashSettings(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppSettings: Hashable {
  var appBadge: Bool
  var tagSaveEnabled: Bool
  var tagSaveLabel: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppSettings? {
    let appBadge = pigeonVar_list[0] as! Bool
    let tagSaveEnabled = pigeonVar_list[1] as! Bool
    let tagSaveLabel = pigeonVar_list[2] as! String

    return AppSettings(
      appBadge: appBadge,
      tagSaveEnabled: tagSaveEnabled,
      tagSaveLabel: tagSaveLabel
    )
  }
  func toList() -> [Any?] {
    return [
      appBadge,
      tagSaveEnabled,
      tagSaveLabel,
    ]
  }
  static func == (lhs: AppSettings, rhs: AppSettings) -> Bool {
    return deepEqualsSettings(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashSettings(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionData: Hashable {
  var serverType: String
  var serverUrl: String
  var apiToken: String? = nil
  var clientId: String? = nil
  var clientSecret: String? = nil
  var accessToken: String? = nil
  var tokenExpiration: String? = nil
  var lastSyncTimestamp: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionData? {
    let serverType = pigeonVar_list[0] as! String
    let serverUrl = pigeonVar_list[1] as! String
    let apiToken: String? = nilOrValue(pigeonVar_list[2])
    let clientId: String? = nilOrValue(pigeonVar_list[3])
    let clientSecret: String? = nilOrValue(pigeonVar_list[4])
    let accessToken: String? = nilOrValue(pigeonVar_list[5])
    let tokenExpiration: String? = nilOrValue(pigeonVar_list[6])
    let lastSyncTimestamp: Int64? = nilOrValue(pigeonVar_list[7])

    return SessionData(
      serverType: serverType,
      serverUrl: serverUrl,
      apiToken: apiToken,
      clientId: clientId,
      clientSecret: clientSecret,
      accessToken: accessToken,
      tokenExpiration: tokenExpiration,
      lastSyncTimestamp: lastSyncTimestamp
    )
  }
  func toList() -> [Any?] {
    return [
      serverType,
      serverUrl,
      apiToken,
      clientId,
      clientSecret,
      accessToken,
      tokenExpiration,
      lastSyncTimestamp,
    ]
  }
  static func == (lhs: SessionData, rhs: SessionData) -> Bool {
    return deepEqualsSettings(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashSettings(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLogEntry: Hashable {
  var time: String
  var level: String
  var loggerName: String
  var message: String
  var error: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLogEntry? {
    let time = pigeonVar_list[0] as! String
    let level = pigeonVar_list[1] as! String
    let loggerName = pigeonVar_list[2] as! String
    let message = pigeonVar_list[3] as! String
    let error: String? = nilOrValue(pigeonVar_list[4])

    return NativeLogEntry(
      time: time,
      level: level,
      loggerName: loggerName,
      message: message,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      time,
      level,
      loggerName,
      message,
      error,
    ]
  }
  static func == (lhs: NativeLogEntry, rhs: NativeLogEntry) -> Bool {
    return deepEqualsSettings(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashSettings(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeLicensePackage: Hashable {
  var name: String
  var body: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeLicensePackage? {
    let name = pigeonVar_list[0] as! String
    let body = pigeonVar_list[1] as! String

    return NativeLicensePackage(
      name: name,
      body: body
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      body,
    ]
  }
  static func == (lhs: NativeLicensePackage, rhs: NativeLicensePackage) -> Bool {
    return deepEqualsSettings(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashSettings(value: toList(), hasher: &hasher)
  }
}

private class SettingsPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AppSettings.fromList(self.readValue() as! [Any?])
    case 130:
      return SessionData.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeLogEntry.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeLicensePackage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SettingsPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppSettings {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? SessionData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLogEntry {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeLicensePackage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SettingsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SettingsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SettingsPigeonCodecWriter(data: data)
  }
}

class SettingsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SettingsPigeonCodec(readerWriter: SettingsPigeonCodecReaderWriter())
}

/// Pushes updated settings state into the native settings screen.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SettingsApi {
  func updateAppSettings(settings: AppSettings) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SettingsApiSetup {
  static var codec: FlutterStandardMessageCodec { SettingsPigeonCodec.shared }
  /// Sets up an instance of `SettingsApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: SettingsApi?, messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateAppSettingsChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.SettingsApi.updateAppSettings\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAppSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! AppSettings
        do {
          try api.updateAppSettings(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateAppSettingsChannel.setMessageHandler(nil)
    }
  }
}
/// Callbacks from the native settings screen to the Dart bridge.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SettingsFlutterApiProtocol {
  func setAppSettings(
    settings settingsArg: AppSettings, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func clearCache(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SettingsFlutterApi: SettingsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SettingsPigeonCodec {
    return SettingsPigeonCodec.shared
  }
  func setAppSettings(
    settings settingsArg: AppSettings, completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.SettingsFlutterApi.setAppSettings\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([settingsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func clearCache(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.SettingsFlutterApi.clearCache\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Callbacks from the native session details screen to the Dart bridge.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol SessionDetailsFlutterApiProtocol {
  func getSessionData(completion: @escaping (Result<SessionData, PigeonError>) -> Void)
  func logout(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func refreshToken(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class SessionDetailsFlutterApi: SessionDetailsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SettingsPigeonCodec {
    return SettingsPigeonCodec.shared
  }
  func getSessionData(completion: @escaping (Result<SessionData, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.SessionDetailsFlutterApi.getSessionData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! SessionData
        completion(.success(result))
      }
    }
  }
  func logout(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.SessionDetailsFlutterApi.logout\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func refreshToken(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.SessionDetailsFlutterApi.refreshToken\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Callbacks from the native log console screen to the Dart bridge.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LogConsoleFlutterApiProtocol {
  func getLogs(
    onlyCurrentRun onlyCurrentRunArg: Bool,
    completion: @escaping (Result<[NativeLogEntry], PigeonError>) -> Void)
  func clearLogs(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LogConsoleFlutterApi: LogConsoleFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SettingsPigeonCodec {
    return SettingsPigeonCodec.shared
  }
  func getLogs(
    onlyCurrentRun onlyCurrentRunArg: Bool,
    completion: @escaping (Result<[NativeLogEntry], PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LogConsoleFlutterApi.getLogs\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([onlyCurrentRunArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [NativeLogEntry]
        completion(.success(result))
      }
    }
  }
  func clearLogs(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LogConsoleFlutterApi.clearLogs\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Callbacks from the native licenses screen to the Dart bridge.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LicensesFlutterApiProtocol {
  func getLicenses(completion: @escaping (Result<[NativeLicensePackage], PigeonError>) -> Void)
}
class LicensesFlutterApi: LicensesFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: SettingsPigeonCodec {
    return SettingsPigeonCodec.shared
  }
  func getLicenses(completion: @escaping (Result<[NativeLicensePackage], PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.LicensesFlutterApi.getLicenses\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [NativeLicensePackage]
        completion(.success(result))
      }
    }
  }
}
