// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(
    code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.",
    details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsNavigationSplit(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsNavigationSplit(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsNavigationSplit(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashNavigationSplit(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
    for item in valueList { deepHashNavigationSplit(value: item, hasher: &hasher) }
    return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys {
      hasher.combine(key)
      deepHashNavigationSplit(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

enum NavigationSearchTextMode: Int {
  case all = 0
  case title = 1
  case content = 2
}

enum NavigationStateFilter: Int {
  case all = 0
  case unread = 1
  case archived = 2
}

/// Article data for a single row in the native article list.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ArticleRowData: Hashable {
  var id: Int64
  var title: String
  var domainName: String? = nil
  var readingTime: Int64
  var previewPictureUrl: String? = nil
  var tags: [String]
  var isArchived: Bool
  var isStarred: Bool
  var url: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ArticleRowData? {
    let id = pigeonVar_list[0] as! Int64
    let title = pigeonVar_list[1] as! String
    let domainName: String? = nilOrValue(pigeonVar_list[2])
    let readingTime = pigeonVar_list[3] as! Int64
    let previewPictureUrl: String? = nilOrValue(pigeonVar_list[4])
    let tags = pigeonVar_list[5] as! [String]
    let isArchived = pigeonVar_list[6] as! Bool
    let isStarred = pigeonVar_list[7] as! Bool
    let url = pigeonVar_list[8] as! String

    return ArticleRowData(
      id: id,
      title: title,
      domainName: domainName,
      readingTime: readingTime,
      previewPictureUrl: previewPictureUrl,
      tags: tags,
      isArchived: isArchived,
      isStarred: isStarred,
      url: url
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      domainName,
      readingTime,
      previewPictureUrl,
      tags,
      isArchived,
      isStarred,
      url,
    ]
  }
  static func == (lhs: ArticleRowData, rhs: ArticleRowData) -> Bool {
    return deepEqualsNavigationSplit(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashNavigationSplit(value: toList(), hasher: &hasher)
  }
}

/// Sync progress state for the toolbar indicator.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NavigationSyncState: Hashable {
  var isWorking: Bool
  var progressValue: Double? = nil
  var pendingCount: Int64

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NavigationSyncState? {
    let isWorking = pigeonVar_list[0] as! Bool
    let progressValue: Double? = nilOrValue(pigeonVar_list[1])
    let pendingCount = pigeonVar_list[2] as! Int64

    return NavigationSyncState(
      isWorking: isWorking,
      progressValue: progressValue,
      pendingCount: pendingCount
    )
  }
  func toList() -> [Any?] {
    return [
      isWorking,
      progressValue,
      pendingCount,
    ]
  }
  static func == (lhs: NavigationSyncState, rhs: NavigationSyncState) -> Bool {
    return deepEqualsNavigationSplit(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashNavigationSplit(value: toList(), hasher: &hasher)
  }
}

/// Mirrors the Query domain model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NavigationFilterState: Hashable {
  var text: String
  var textMode: NavigationSearchTextMode
  var stateFilter: NavigationStateFilter
  var onlyStarred: Bool
  var tags: [String]
  var domains: [String]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NavigationFilterState? {
    let text = pigeonVar_list[0] as! String
    let textMode = pigeonVar_list[1] as! NavigationSearchTextMode
    let stateFilter = pigeonVar_list[2] as! NavigationStateFilter
    let onlyStarred = pigeonVar_list[3] as! Bool
    let tags = pigeonVar_list[4] as! [String]
    let domains = pigeonVar_list[5] as! [String]

    return NavigationFilterState(
      text: text,
      textMode: textMode,
      stateFilter: stateFilter,
      onlyStarred: onlyStarred,
      tags: tags,
      domains: domains
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      textMode,
      stateFilter,
      onlyStarred,
      tags,
      domains,
    ]
  }
  static func == (lhs: NavigationFilterState, rhs: NavigationFilterState) -> Bool {
    return deepEqualsNavigationSplit(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashNavigationSplit(value: toList(), hasher: &hasher)
  }
}

/// Reading settings for the native article WebView.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ArticleReadingSettings: Hashable {
  var fontSize: Double
  var fontFamily: String
  var justifyText: Bool

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ArticleReadingSettings? {
    let fontSize = pigeonVar_list[0] as! Double
    let fontFamily = pigeonVar_list[1] as! String
    let justifyText = pigeonVar_list[2] as! Bool

    return ArticleReadingSettings(
      fontSize: fontSize,
      fontFamily: fontFamily,
      justifyText: justifyText
    )
  }
  func toList() -> [Any?] {
    return [
      fontSize,
      fontFamily,
      justifyText,
    ]
  }
  static func == (lhs: ArticleReadingSettings, rhs: ArticleReadingSettings) -> Bool {
    return deepEqualsNavigationSplit(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashNavigationSplit(value: toList(), hasher: &hasher)
  }
}

/// Article content pushed into the native detail view.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ArticleContent: Hashable {
  var id: Int64
  var html: String? = nil
  var readingProgress: Double

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ArticleContent? {
    let id = pigeonVar_list[0] as! Int64
    let html: String? = nilOrValue(pigeonVar_list[1])
    let readingProgress = pigeonVar_list[2] as! Double

    return ArticleContent(
      id: id,
      html: html,
      readingProgress: readingProgress
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      html,
      readingProgress,
    ]
  }
  static func == (lhs: ArticleContent, rhs: ArticleContent) -> Bool {
    return deepEqualsNavigationSplit(lhs.toList(), rhs.toList())
  }
  func hash(into hasher: inout Hasher) {
    deepHashNavigationSplit(value: toList(), hasher: &hasher)
  }
}

private class NavigationSplitPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NavigationSearchTextMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NavigationStateFilter(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return ArticleRowData.fromList(self.readValue() as! [Any?])
    case 132:
      return NavigationSyncState.fromList(self.readValue() as! [Any?])
    case 133:
      return NavigationFilterState.fromList(self.readValue() as! [Any?])
    case 134:
      return ArticleReadingSettings.fromList(self.readValue() as! [Any?])
    case 135:
      return ArticleContent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class NavigationSplitPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NavigationSearchTextMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NavigationStateFilter {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ArticleRowData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationSyncState {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NavigationFilterState {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ArticleReadingSettings {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ArticleContent {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class NavigationSplitPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NavigationSplitPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NavigationSplitPigeonCodecWriter(data: data)
  }
}

class NavigationSplitPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NavigationSplitPigeonCodec(
    readerWriter: NavigationSplitPigeonCodecReaderWriter())
}

/// Dart → Swift. Pushes updated list/sync/filter state into the native sidebar.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NavigationSplitApi {
  func updateArticleIds(ids: [Int64]) throws
  func updateSyncState(state: NavigationSyncState) throws
  func updateFilterState(state: NavigationFilterState) throws
  func updateArticleContent(content: ArticleContent) throws
  func updateArticleData(data: ArticleRowData) throws
  func updateReadingSettings(settings: ArticleReadingSettings) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NavigationSplitApiSetup {
  static var codec: FlutterStandardMessageCodec { NavigationSplitPigeonCodec.shared }
  /// Sets up an instance of `NavigationSplitApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: NavigationSplitApi?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateArticleIdsChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateArticleIds\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateArticleIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idsArg = args[0] as! [Int64]
        do {
          try api.updateArticleIds(ids: idsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateArticleIdsChannel.setMessageHandler(nil)
    }
    let updateSyncStateChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateSyncState\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSyncStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = args[0] as! NavigationSyncState
        do {
          try api.updateSyncState(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateSyncStateChannel.setMessageHandler(nil)
    }
    let updateFilterStateChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateFilterState\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateFilterStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = args[0] as! NavigationFilterState
        do {
          try api.updateFilterState(state: stateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateFilterStateChannel.setMessageHandler(nil)
    }
    let updateArticleContentChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateArticleContent\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateArticleContentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contentArg = args[0] as! ArticleContent
        do {
          try api.updateArticleContent(content: contentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateArticleContentChannel.setMessageHandler(nil)
    }
    let updateArticleDataChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateArticleData\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateArticleDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! ArticleRowData
        do {
          try api.updateArticleData(data: dataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateArticleDataChannel.setMessageHandler(nil)
    }
    let updateReadingSettingsChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateReadingSettings\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateReadingSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let settingsArg = args[0] as! ArticleReadingSettings
        do {
          try api.updateReadingSettings(settings: settingsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateReadingSettingsChannel.setMessageHandler(nil)
    }
  }
}
/// Swift → Dart. Callbacks from the native sidebar to the Dart bridge.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NavigationSplitFlutterApiProtocol {
  func getArticleRowData(
    id idArg: Int64, completion: @escaping (Result<ArticleRowData, PigeonError>) -> Void)
  func getAvailableTags(completion: @escaping (Result<[String], PigeonError>) -> Void)
  func getAvailableDomains(completion: @escaping (Result<[String], PigeonError>) -> Void)
  func setSearchText(
    text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setTextMode(
    mode modeArg: NavigationSearchTextMode,
    completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setStateFilter(
    state stateArg: NavigationStateFilter, completion: @escaping (Result<Void, PigeonError>) -> Void
  )
  func setOnlyStarred(
    onlyStarred onlyStarredArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setTags(tags tagsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setDomains(
    domains domainsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func refresh(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setArticleArchived(
    id idArg: Int64, archived archivedArg: Bool,
    completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setArticleStarred(
    id idArg: Int64, starred starredArg: Bool,
    completion: @escaping (Result<Void, PigeonError>) -> Void)
  func filterByTag(tag tagArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onArticleSelected(id idArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onReadingProgressChanged(
    articleId articleIdArg: Int64, progress progressArg: Double,
    completion: @escaping (Result<Void, PigeonError>) -> Void)
  func deleteArticle(id idArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func openArticleSheet(id idArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setReadingSettings(
    settings settingsArg: ArticleReadingSettings,
    completion: @escaping (Result<Void, PigeonError>) -> Void)
  func openSettings(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func secondaryScreenDidClose(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func saveLink(url urlArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class NavigationSplitFlutterApi: NavigationSplitFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NavigationSplitPigeonCodec {
    return NavigationSplitPigeonCodec.shared
  }
  func getArticleRowData(
    id idArg: Int64, completion: @escaping (Result<ArticleRowData, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getArticleRowData\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ArticleRowData
        completion(.success(result))
      }
    }
  }
  func getAvailableTags(completion: @escaping (Result<[String], PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getAvailableTags\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [String]
        completion(.success(result))
      }
    }
  }
  func getAvailableDomains(completion: @escaping (Result<[String], PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getAvailableDomains\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(
          .failure(
            PigeonError(
              code: "null-error",
              message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [String]
        completion(.success(result))
      }
    }
  }
  func setSearchText(
    text textArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setSearchText\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([textArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setTextMode(
    mode modeArg: NavigationSearchTextMode,
    completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTextMode\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([modeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setStateFilter(
    state stateArg: NavigationStateFilter, completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setStateFilter\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setOnlyStarred(
    onlyStarred onlyStarredArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setOnlyStarred\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([onlyStarredArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setTags(tags tagsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTags\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tagsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setDomains(
    domains domainsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setDomains\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([domainsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func refresh(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.refresh\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setArticleArchived(
    id idArg: Int64, archived archivedArg: Bool,
    completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleArchived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg, archivedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setArticleStarred(
    id idArg: Int64, starred starredArg: Bool,
    completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleStarred\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg, starredArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func filterByTag(tag tagArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.filterByTag\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tagArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onArticleSelected(id idArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onArticleSelected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onReadingProgressChanged(
    articleId articleIdArg: Int64, progress progressArg: Double,
    completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onReadingProgressChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([articleIdArg, progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func deleteArticle(id idArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.deleteArticle\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func openArticleSheet(id idArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.openArticleSheet\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setReadingSettings(
    settings settingsArg: ArticleReadingSettings,
    completion: @escaping (Result<Void, PigeonError>) -> Void
  ) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setReadingSettings\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([settingsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func openSettings(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.openSettings\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func secondaryScreenDidClose(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.secondaryScreenDidClose\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func saveLink(url urlArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String =
      "dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.saveLink\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(
      name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([urlArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
