// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

class ServerCheckResult {
  ServerCheckResult({
    this.serverType,
    this.serverUrl,
    this.version,
    required this.selfSigned,
    this.errorKind,
    this.errorMessage,
  });

  String? serverType;

  String? serverUrl;

  String? version;

  bool selfSigned;

  String? errorKind;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      serverType,
      serverUrl,
      version,
      selfSigned,
      errorKind,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ServerCheckResult decode(Object result) {
    result as List<Object?>;
    return ServerCheckResult(
      serverType: result[0] as String?,
      serverUrl: result[1] as String?,
      version: result[2] as String?,
      selfSigned: result[3]! as bool,
      errorKind: result[4] as String?,
      errorMessage: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ServerCheckResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ServerCheckResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ServerCheckResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native login screen callbacks to Dart.
abstract class LoginFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<ServerCheckResult> checkServer(String url, bool selfSigned);

  Future<String?> loginWallabag(
    String url,
    bool selfSigned,
    String clientId,
    String clientSecret,
    String username,
    String password,
  );

  Future<String?> loginFreon(String url, bool selfSigned, String token);

  Future<void> loadDemoMode();

  static void setUp(
    LoginFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LoginFlutterApi.checkServer$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.checkServer was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          assert(
            arg_url != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.checkServer was null, expected non-null String.',
          );
          final bool? arg_selfSigned = (args[1] as bool?);
          assert(
            arg_selfSigned != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.checkServer was null, expected non-null bool.',
          );
          try {
            final ServerCheckResult output = await api.checkServer(
              arg_url!,
              arg_selfSigned!,
            );
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          assert(
            arg_url != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null, expected non-null String.',
          );
          final bool? arg_selfSigned = (args[1] as bool?);
          assert(
            arg_selfSigned != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null, expected non-null bool.',
          );
          final String? arg_clientId = (args[2] as String?);
          assert(
            arg_clientId != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null, expected non-null String.',
          );
          final String? arg_clientSecret = (args[3] as String?);
          assert(
            arg_clientSecret != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null, expected non-null String.',
          );
          final String? arg_username = (args[4] as String?);
          assert(
            arg_username != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null, expected non-null String.',
          );
          final String? arg_password = (args[5] as String?);
          assert(
            arg_password != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginWallabag was null, expected non-null String.',
          );
          try {
            final String? output = await api.loginWallabag(
              arg_url!,
              arg_selfSigned!,
              arg_clientId!,
              arg_clientSecret!,
              arg_username!,
              arg_password!,
            );
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginFreon$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginFreon was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          assert(
            arg_url != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginFreon was null, expected non-null String.',
          );
          final bool? arg_selfSigned = (args[1] as bool?);
          assert(
            arg_selfSigned != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginFreon was null, expected non-null bool.',
          );
          final String? arg_token = (args[2] as String?);
          assert(
            arg_token != null,
            'Argument for dev.flutter.pigeon.frigoligo.LoginFlutterApi.loginFreon was null, expected non-null String.',
          );
          try {
            final String? output = await api.loginFreon(
              arg_url!,
              arg_selfSigned!,
              arg_token!,
            );
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LoginFlutterApi.loadDemoMode$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.loadDemoMode();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
