// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum NavigationSearchTextMode { all, title, content }

enum NavigationStateFilter { all, unread, archived }

/// Article data for a single row in the native article list.
class ArticleRowData {
  ArticleRowData({
    required this.id,
    required this.title,
    this.domainName,
    required this.readingTime,
    this.previewPictureUrl,
    required this.tags,
    required this.isArchived,
    required this.isStarred,
    required this.url,
  });

  int id;

  String title;

  String? domainName;

  int readingTime;

  String? previewPictureUrl;

  List<String> tags;

  bool isArchived;

  bool isStarred;

  String url;

  List<Object?> _toList() {
    return <Object?>[
      id,
      title,
      domainName,
      readingTime,
      previewPictureUrl,
      tags,
      isArchived,
      isStarred,
      url,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ArticleRowData decode(Object result) {
    result as List<Object?>;
    return ArticleRowData(
      id: result[0]! as int,
      title: result[1]! as String,
      domainName: result[2] as String?,
      readingTime: result[3]! as int,
      previewPictureUrl: result[4] as String?,
      tags: (result[5] as List<Object?>?)!.cast<String>(),
      isArchived: result[6]! as bool,
      isStarred: result[7]! as bool,
      url: result[8]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ArticleRowData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Sync progress state for the toolbar indicator.
class NavigationSyncState {
  NavigationSyncState({
    required this.isWorking,
    this.progressValue,
    required this.pendingCount,
  });

  bool isWorking;

  double? progressValue;

  int pendingCount;

  List<Object?> _toList() {
    return <Object?>[isWorking, progressValue, pendingCount];
  }

  Object encode() {
    return _toList();
  }

  static NavigationSyncState decode(Object result) {
    result as List<Object?>;
    return NavigationSyncState(
      isWorking: result[0]! as bool,
      progressValue: result[1] as double?,
      pendingCount: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationSyncState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Mirrors the Query domain model for active filter state.
class NavigationFilterState {
  NavigationFilterState({
    required this.text,
    required this.textMode,
    required this.stateFilter,
    required this.onlyStarred,
    required this.tags,
    required this.domains,
  });

  String text;

  NavigationSearchTextMode textMode;

  NavigationStateFilter stateFilter;

  bool onlyStarred;

  List<String> tags;

  List<String> domains;

  List<Object?> _toList() {
    return <Object?>[text, textMode, stateFilter, onlyStarred, tags, domains];
  }

  Object encode() {
    return _toList();
  }

  static NavigationFilterState decode(Object result) {
    result as List<Object?>;
    return NavigationFilterState(
      text: result[0]! as String,
      textMode: result[1]! as NavigationSearchTextMode,
      stateFilter: result[2]! as NavigationStateFilter,
      onlyStarred: result[3]! as bool,
      tags: (result[4] as List<Object?>?)!.cast<String>(),
      domains: (result[5] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NavigationFilterState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Reading settings for the native article WebView.
class ArticleReadingSettings {
  ArticleReadingSettings({
    required this.fontSize,
    required this.fontFamily,
    required this.justifyText,
  });

  double fontSize;

  String fontFamily;

  bool justifyText;

  List<Object?> _toList() {
    return <Object?>[fontSize, fontFamily, justifyText];
  }

  Object encode() {
    return _toList();
  }

  static ArticleReadingSettings decode(Object result) {
    result as List<Object?>;
    return ArticleReadingSettings(
      fontSize: result[0]! as double,
      fontFamily: result[1]! as String,
      justifyText: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ArticleReadingSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Article content pushed into the native detail view.
class ArticleContent {
  ArticleContent({required this.id, this.html, required this.readingProgress});

  int id;

  String? html;

  double readingProgress;

  List<Object?> _toList() {
    return <Object?>[id, html, readingProgress];
  }

  Object encode() {
    return _toList();
  }

  static ArticleContent decode(Object result) {
    result as List<Object?>;
    return ArticleContent(
      id: result[0]! as int,
      html: result[1] as String?,
      readingProgress: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ArticleContent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NavigationSearchTextMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is NavigationStateFilter) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is ArticleRowData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NavigationSyncState) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is NavigationFilterState) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ArticleReadingSettings) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is ArticleContent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NavigationSearchTextMode.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NavigationStateFilter.values[value];
      case 131:
        return ArticleRowData.decode(readValue(buffer)!);
      case 132:
        return NavigationSyncState.decode(readValue(buffer)!);
      case 133:
        return NavigationFilterState.decode(readValue(buffer)!);
      case 134:
        return ArticleReadingSettings.decode(readValue(buffer)!);
      case 135:
        return ArticleContent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart → Swift. Pushes updated list/sync/filter state into the native sidebar.
class NavigationSplitApi {
  /// Constructor for [NavigationSplitApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NavigationSplitApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> updateArticleIds(List<int> ids) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateArticleIds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[ids],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateSyncState(NavigationSyncState state) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateSyncState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[state],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateFilterState(NavigationFilterState state) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateFilterState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[state],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateArticleContent(ArticleContent content) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateArticleContent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[content],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateArticleData(ArticleRowData data) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateArticleData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[data],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateReadingSettings(ArticleReadingSettings settings) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.NavigationSplitApi.updateReadingSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[settings],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Swift → Dart. Callbacks from the native sidebar to the Dart bridge.
abstract class NavigationSplitFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<ArticleRowData> getArticleRowData(int id);

  void setSearchText(String text);

  void setTextMode(NavigationSearchTextMode mode);

  void setStateFilter(NavigationStateFilter state);

  void setOnlyStarred(bool onlyStarred);

  void setTags(List<String> tags);

  void setDomains(List<String> domains);

  Future<List<String>> getAvailableTags();

  Future<List<String>> getAvailableDomains();

  Future<void> refresh();

  Future<void> setArticleArchived(int id, bool archived);

  Future<void> setArticleStarred(int id, bool starred);

  void filterByTag(String tag);

  Future<void> onArticleSelected(int id);

  Future<void> onReadingProgressChanged(int articleId, double progress);

  Future<void> deleteArticle(int id);

  Future<void> openArticleSheet(int id);

  Future<void> setReadingSettings(ArticleReadingSettings settings);

  Future<void> openSettings();

  Future<void> secondaryScreenDidClose();

  Future<void> saveLink(String url);

  static void setUp(
    NavigationSplitFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getArticleRowData$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getArticleRowData was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(
            arg_id != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getArticleRowData was null, expected non-null int.',
          );
          try {
            final ArticleRowData output = await api.getArticleRowData(arg_id!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setSearchText$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setSearchText was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_text = (args[0] as String?);
          assert(
            arg_text != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setSearchText was null, expected non-null String.',
          );
          try {
            api.setSearchText(arg_text!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTextMode$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTextMode was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final NavigationSearchTextMode? arg_mode =
              (args[0] as NavigationSearchTextMode?);
          assert(
            arg_mode != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTextMode was null, expected non-null NavigationSearchTextMode.',
          );
          try {
            api.setTextMode(arg_mode!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setStateFilter$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setStateFilter was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final NavigationStateFilter? arg_state =
              (args[0] as NavigationStateFilter?);
          assert(
            arg_state != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setStateFilter was null, expected non-null NavigationStateFilter.',
          );
          try {
            api.setStateFilter(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setOnlyStarred$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setOnlyStarred was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_onlyStarred = (args[0] as bool?);
          assert(
            arg_onlyStarred != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setOnlyStarred was null, expected non-null bool.',
          );
          try {
            api.setOnlyStarred(arg_onlyStarred!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTags$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTags was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final List<String>? arg_tags = (args[0] as List<Object?>?)
              ?.cast<String>();
          assert(
            arg_tags != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setTags was null, expected non-null List<String>.',
          );
          try {
            api.setTags(arg_tags!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setDomains$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setDomains was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final List<String>? arg_domains = (args[0] as List<Object?>?)
              ?.cast<String>();
          assert(
            arg_domains != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setDomains was null, expected non-null List<String>.',
          );
          try {
            api.setDomains(arg_domains!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getAvailableTags$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final List<String> output = await api.getAvailableTags();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.getAvailableDomains$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final List<String> output = await api.getAvailableDomains();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.refresh$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.refresh();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleArchived$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleArchived was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(
            arg_id != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleArchived was null, expected non-null int.',
          );
          final bool? arg_archived = (args[1] as bool?);
          assert(
            arg_archived != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleArchived was null, expected non-null bool.',
          );
          try {
            await api.setArticleArchived(arg_id!, arg_archived!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleStarred$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleStarred was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(
            arg_id != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleStarred was null, expected non-null int.',
          );
          final bool? arg_starred = (args[1] as bool?);
          assert(
            arg_starred != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setArticleStarred was null, expected non-null bool.',
          );
          try {
            await api.setArticleStarred(arg_id!, arg_starred!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.filterByTag$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.filterByTag was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_tag = (args[0] as String?);
          assert(
            arg_tag != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.filterByTag was null, expected non-null String.',
          );
          try {
            api.filterByTag(arg_tag!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onArticleSelected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onArticleSelected was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(
            arg_id != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onArticleSelected was null, expected non-null int.',
          );
          try {
            await api.onArticleSelected(arg_id!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onReadingProgressChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onReadingProgressChanged was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_articleId = (args[0] as int?);
          assert(
            arg_articleId != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onReadingProgressChanged was null, expected non-null int.',
          );
          final double? arg_progress = (args[1] as double?);
          assert(
            arg_progress != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.onReadingProgressChanged was null, expected non-null double.',
          );
          try {
            await api.onReadingProgressChanged(arg_articleId!, arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.deleteArticle$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.deleteArticle was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(
            arg_id != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.deleteArticle was null, expected non-null int.',
          );
          try {
            await api.deleteArticle(arg_id!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.openArticleSheet$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.openArticleSheet was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_id = (args[0] as int?);
          assert(
            arg_id != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.openArticleSheet was null, expected non-null int.',
          );
          try {
            await api.openArticleSheet(arg_id!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setReadingSettings$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setReadingSettings was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final ArticleReadingSettings? arg_settings =
              (args[0] as ArticleReadingSettings?);
          assert(
            arg_settings != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.setReadingSettings was null, expected non-null ArticleReadingSettings.',
          );
          try {
            await api.setReadingSettings(arg_settings!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.openSettings$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.openSettings();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.secondaryScreenDidClose$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.secondaryScreenDidClose();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.saveLink$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.saveLink was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          assert(
            arg_url != null,
            'Argument for dev.flutter.pigeon.frigoligo.NavigationSplitFlutterApi.saveLink was null, expected non-null String.',
          );
          try {
            await api.saveLink(arg_url!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
