// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

class AppSettings {
  AppSettings({
    required this.appBadge,
    required this.tagSaveEnabled,
    required this.tagSaveLabel,
  });

  bool appBadge;

  bool tagSaveEnabled;

  String tagSaveLabel;

  List<Object?> _toList() {
    return <Object?>[appBadge, tagSaveEnabled, tagSaveLabel];
  }

  Object encode() {
    return _toList();
  }

  static AppSettings decode(Object result) {
    result as List<Object?>;
    return AppSettings(
      appBadge: result[0]! as bool,
      tagSaveEnabled: result[1]! as bool,
      tagSaveLabel: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppSettings || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class SessionData {
  SessionData({
    required this.serverType,
    required this.serverUrl,
    this.apiToken,
    this.clientId,
    this.clientSecret,
    this.accessToken,
    this.tokenExpiration,
    this.lastSyncTimestamp,
  });

  String serverType;

  String serverUrl;

  String? apiToken;

  String? clientId;

  String? clientSecret;

  String? accessToken;

  String? tokenExpiration;

  int? lastSyncTimestamp;

  List<Object?> _toList() {
    return <Object?>[
      serverType,
      serverUrl,
      apiToken,
      clientId,
      clientSecret,
      accessToken,
      tokenExpiration,
      lastSyncTimestamp,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SessionData decode(Object result) {
    result as List<Object?>;
    return SessionData(
      serverType: result[0]! as String,
      serverUrl: result[1]! as String,
      apiToken: result[2] as String?,
      clientId: result[3] as String?,
      clientSecret: result[4] as String?,
      accessToken: result[5] as String?,
      tokenExpiration: result[6] as String?,
      lastSyncTimestamp: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class NativeLogEntry {
  NativeLogEntry({
    required this.time,
    required this.level,
    required this.loggerName,
    required this.message,
    this.error,
  });

  String time;

  String level;

  String loggerName;

  String message;

  String? error;

  List<Object?> _toList() {
    return <Object?>[time, level, loggerName, message, error];
  }

  Object encode() {
    return _toList();
  }

  static NativeLogEntry decode(Object result) {
    result as List<Object?>;
    return NativeLogEntry(
      time: result[0]! as String,
      level: result[1]! as String,
      loggerName: result[2]! as String,
      message: result[3]! as String,
      error: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLogEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class NativeLicensePackage {
  NativeLicensePackage({required this.name, required this.body});

  String name;

  String body;

  List<Object?> _toList() {
    return <Object?>[name, body];
  }

  Object encode() {
    return _toList();
  }

  static NativeLicensePackage decode(Object result) {
    result as List<Object?>;
    return NativeLicensePackage(
      name: result[0]! as String,
      body: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLicensePackage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AppSettings) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is SessionData) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativeLogEntry) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeLicensePackage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AppSettings.decode(readValue(buffer)!);
      case 130:
        return SessionData.decode(readValue(buffer)!);
      case 131:
        return NativeLogEntry.decode(readValue(buffer)!);
      case 132:
        return NativeLicensePackage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Pushes updated settings state into the native settings screen.
class SettingsApi {
  /// Constructor for [SettingsApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SettingsApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> updateAppSettings(AppSettings settings) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.frigoligo.SettingsApi.updateAppSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[settings],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Callbacks from the native settings screen to the Dart bridge.
abstract class SettingsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> setAppSettings(AppSettings settings);

  Future<void> clearCache();

  static void setUp(
    SettingsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.SettingsFlutterApi.setAppSettings$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.SettingsFlutterApi.setAppSettings was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final AppSettings? arg_settings = (args[0] as AppSettings?);
          assert(
            arg_settings != null,
            'Argument for dev.flutter.pigeon.frigoligo.SettingsFlutterApi.setAppSettings was null, expected non-null AppSettings.',
          );
          try {
            await api.setAppSettings(arg_settings!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.SettingsFlutterApi.clearCache$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.clearCache();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Callbacks from the native session details screen to the Dart bridge.
abstract class SessionDetailsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<SessionData> getSessionData();

  Future<void> logout();

  Future<void> refreshToken();

  static void setUp(
    SessionDetailsFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.SessionDetailsFlutterApi.getSessionData$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final SessionData output = await api.getSessionData();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.SessionDetailsFlutterApi.logout$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.logout();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.SessionDetailsFlutterApi.refreshToken$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.refreshToken();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Callbacks from the native log console screen to the Dart bridge.
abstract class LogConsoleFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<List<NativeLogEntry>> getLogs(bool onlyCurrentRun);

  Future<void> clearLogs();

  static void setUp(
    LogConsoleFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LogConsoleFlutterApi.getLogs$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.frigoligo.LogConsoleFlutterApi.getLogs was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final bool? arg_onlyCurrentRun = (args[0] as bool?);
          assert(
            arg_onlyCurrentRun != null,
            'Argument for dev.flutter.pigeon.frigoligo.LogConsoleFlutterApi.getLogs was null, expected non-null bool.',
          );
          try {
            final List<NativeLogEntry> output = await api.getLogs(
              arg_onlyCurrentRun!,
            );
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LogConsoleFlutterApi.clearLogs$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            await api.clearLogs();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}

/// Callbacks from the native licenses screen to the Dart bridge.
abstract class LicensesFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<List<NativeLicensePackage>> getLicenses();

  static void setUp(
    LicensesFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.frigoligo.LicensesFlutterApi.getLicenses$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            final List<NativeLicensePackage> output = await api.getLicenses();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
