# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do |lane|
  Dotenv.overload "../.env"
end

platform :android do
  desc "Upload metadata to the Google Play Store"
  lane :upload_metadata do
    supply(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      sync_image_upload: true
    )
  end
end

platform :ios do
  desc "Upload metadata to the App Store"
  lane :upload_metadata do
    deliver(
      metadata_path: "fastlane/metadata/ios/",
      screenshots_path: "fastlane/screenshots/ios/"
    )
  end
end
