// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsArticleSheet(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsArticleSheet(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsArticleSheet(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashArticleSheet(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashArticleSheet(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashArticleSheet(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct ArticleSheetLabels: Hashable {
  var addTags: String
  var openInBrowser: String
  var readingTime: String
  var refetchContent: String
  var share: String
  var sheetTitle: String
  var tags: String
  var title: String
  var website: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ArticleSheetLabels? {
    let addTags = pigeonVar_list[0] as! String
    let openInBrowser = pigeonVar_list[1] as! String
    let readingTime = pigeonVar_list[2] as! String
    let refetchContent = pigeonVar_list[3] as! String
    let share = pigeonVar_list[4] as! String
    let sheetTitle = pigeonVar_list[5] as! String
    let tags = pigeonVar_list[6] as! String
    let title = pigeonVar_list[7] as! String
    let website = pigeonVar_list[8] as! String

    return ArticleSheetLabels(
      addTags: addTags,
      openInBrowser: openInBrowser,
      readingTime: readingTime,
      refetchContent: refetchContent,
      share: share,
      sheetTitle: sheetTitle,
      tags: tags,
      title: title,
      website: website
    )
  }
  func toList() -> [Any?] {
    return [
      addTags,
      openInBrowser,
      readingTime,
      refetchContent,
      share,
      sheetTitle,
      tags,
      title,
      website,
    ]
  }
  static func == (lhs: ArticleSheetLabels, rhs: ArticleSheetLabels) -> Bool {
    return deepEqualsArticleSheet(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashArticleSheet(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ArticleSheetData: Hashable {
  var title: String? = nil
  var link: String? = nil
  var domain: String? = nil
  var readingTime: String? = nil
  var tags: [String]? = nil
  var labels: ArticleSheetLabels


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ArticleSheetData? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let link: String? = nilOrValue(pigeonVar_list[1])
    let domain: String? = nilOrValue(pigeonVar_list[2])
    let readingTime: String? = nilOrValue(pigeonVar_list[3])
    let tags: [String]? = nilOrValue(pigeonVar_list[4])
    let labels = pigeonVar_list[5] as! ArticleSheetLabels

    return ArticleSheetData(
      title: title,
      link: link,
      domain: domain,
      readingTime: readingTime,
      tags: tags,
      labels: labels
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      link,
      domain,
      readingTime,
      tags,
      labels,
    ]
  }
  static func == (lhs: ArticleSheetData, rhs: ArticleSheetData) -> Bool {
    return deepEqualsArticleSheet(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashArticleSheet(value: toList(), hasher: &hasher)
  }
}

private class ArticleSheetPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ArticleSheetLabels.fromList(self.readValue() as! [Any?])
    case 130:
      return ArticleSheetData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ArticleSheetPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ArticleSheetLabels {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ArticleSheetData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ArticleSheetPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ArticleSheetPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ArticleSheetPigeonCodecWriter(data: data)
  }
}

class ArticleSheetPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ArticleSheetPigeonCodec(readerWriter: ArticleSheetPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ArticleSheetApi {
  func open() throws
  func update(data: ArticleSheetData) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ArticleSheetApiSetup {
  static var codec: FlutterStandardMessageCodec { ArticleSheetPigeonCodec.shared }
  /// Sets up an instance of `ArticleSheetApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ArticleSheetApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.frigoligo.ArticleSheetApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { _, reply in
        do {
          try api.open()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let updateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.frigoligo.ArticleSheetApi.update\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! ArticleSheetData
        do {
          try api.update(data: dataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ArticleSheetFlutterApiProtocol {
  func close(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func getAllTags(completion: @escaping (Result<[String], PigeonError>) -> Void)
  func refetchContent(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setTags(tags tagsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ArticleSheetFlutterApi: ArticleSheetFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ArticleSheetPigeonCodec {
    return ArticleSheetPigeonCodec.shared
  }
  func close(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.frigoligo.ArticleSheetFlutterApi.close\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func getAllTags(completion: @escaping (Result<[String], PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.frigoligo.ArticleSheetFlutterApi.getAllTags\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [String]
        completion(.success(result))
      }
    }
  }
  func refetchContent(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.frigoligo.ArticleSheetFlutterApi.refetchContent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setTags(tags tagsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.frigoligo.ArticleSheetFlutterApi.setTags\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tagsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
