name: code analysis

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "version=$(jq -r '.flutter' .fvmrc)" >> $GITHUB_OUTPUT
        shell: bash
        id: flutter-version
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          cache: true
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
