name: flutter tests

on:
  push:
    branches:
      - main
    tags:
      - dependencies
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "version=$(jq -r '.flutter' .fvmrc)" >> $GITHUB_OUTPUT
        shell: bash
        id: flutter-version
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          cache: true
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  smoke-platform-run:
    needs: tests
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "version=$(jq -r '.flutter' .fvmrc)" >> $GITHUB_OUTPUT
        shell: bash
        id: flutter-version
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          cache: true
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter test test/smoke_test.dart

  smoke-android-build:
    # for android we only validate the build process, running is too complicated
    needs: tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - run: echo "version=$(jq -r '.flutter' .fvmrc)" >> $GITHUB_OUTPUT
        id: flutter-version
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          cache: true
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter build apk

  smoke-web-build:
    # for web we only validate the build process, running is too complicated
    needs: tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "version=$(jq -r '.flutter' .fvmrc)" >> $GITHUB_OUTPUT
        id: flutter-version
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          cache: true
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter build web
