name: release artifacts
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.export.outputs.VERSION }}
      ARTIFACT_ANDROID: ${{ steps.export.outputs.ARTIFACT_ANDROID }}
      ARTIFACT_LINUX_X64: ${{ steps.export.outputs.ARTIFACT_LINUX_X64 }}
      ARTIFACT_WINDOWS: ${{ steps.export.outputs.ARTIFACT_WINDOWS }}
    steps:
      - shell: bash
        run: | 
          echo "release_version=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          echo "artifact_prefix=frigoligo-${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
      - id: export
        run: |
          echo "VERSION=${{ env.release_version }}" >> "$GITHUB_OUTPUT"
          echo "ARTIFACT_ANDROID=${{ env.artifact_prefix }}-unsigned.apk" >> "$GITHUB_OUTPUT"
          echo "ARTIFACT_LINUX_X64=${{ env.artifact_prefix }}-linux-x64.tar.gz" >> "$GITHUB_OUTPUT"
          echo "ARTIFACT_WINDOWS=${{ env.artifact_prefix }}-windows-x64.zip" >> "$GITHUB_OUTPUT"

  build_apk:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.setup.outputs.ARTIFACT_ANDROID }}
          path: build/app/outputs/flutter-apk/app-release.apk
      - if: ${{ github.ref_type == 'tag' }}
        run: gh release upload ${{ github.ref_name }} ${{ needs.setup.outputs.ARTIFACT_ANDROID }} --clobber


  build_linux:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build linux
      - run: tar czf ${{ needs.setup.outputs.ARTIFACT_LINUX_X64 }} build/linux/x64/release/bundle/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.setup.outputs.ARTIFACT_LINUX_X64 }}
          path: ${{ needs.setup.outputs.ARTIFACT_LINUX_X64 }}
      - if: ${{ github.ref_type == 'tag' }}
        run: gh release upload ${{ github.ref_name }} ${{ needs.setup.outputs.ARTIFACT_LINUX_X64 }} --clobber

  build_windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath ${{ needs.setup.outputs.ARTIFACT_WINDOWS }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.setup.outputs.ARTIFACT_WINDOWS }}
          path: ${{ needs.setup.outputs.ARTIFACT_WINDOWS }}
      - if: ${{ github.ref_type == 'tag' }}
        run: gh release upload ${{ github.ref_name }} ${{ needs.setup.outputs.ARTIFACT_WINDOWS }} --clobber
