name: release artifacts
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  env_setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "release_version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        shell: bash
      - run: echo "artifact_prefix=frigoligo-${{ env.release_version }}" >> $GITHUB_ENV

  build_apk:
    needs: env_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_prefix }}-unsigned.apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - if: github.ref_type == "tag"
        run: gh release upload ${{ env.artifact_prefix }}-unsigned.apk --clobber


  build_linux:
    needs: env_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build linux
      - run: tar czf ${{ env.artifact_prefix }}-linux-x64.tar.gz build/linux/x64/release/bundle/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_prefix }}-linux-x64.tar.gz
          path: ${{ env.artifact_prefix }}-linux-x64.tar.gz
      - if: github.ref_type == "tag"
        run: gh release upload ${{ env.artifact_prefix }}-linux-x64.tar.gz --clobber

  build_windows:
    needs: env_setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath ${{ env.artifact_prefix }}-windows-x64.zip
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_prefix }}-windows-x64.zip
          path: ${{ env.artifact_prefix }}-windows-x64.zip
      - if: github.ref_type == "tag"
        run: gh release upload ${{ env.artifact_prefix }}-windows-x64.zip --clobber
